### ISSUE TITLE
Trouble compiling weith UM TinyPICO

### ISSUE THREAD

**Issue by sanderant** [jonnybergdahl/Arduino_JBWopr_Library#1]
Just want to say first this is awesome you made it!!! THANK YOU SO MUCH!!

I have a TinyPICO version with the sound shield from way back before HAXOR, but it doesn't compile when I choose UM TinyPICO as the board. Do I need to select a different board?

Below is the output:

In file included from C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:96,
                 from C:\Users\Blanco\Documents\Arduino\libraries\JBWopr\src/jbwoprwifi.h:13,
                 from C:\Users\Blanco\Documents\Arduino\libraries\JBWopr\src/jbwoprmqtt.h:12,
                 from C:\Users\Blanco\Documents\Arduino\libraries\JBWopr\src/jbwoprha.h:12,
                 from C:\Users\Blanco\Documents\Arduino\Arduino_JBWopr_Library\examples\JBWopr_Firmware\JBWopr_Firmware.ino:38:
C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/strings_en.h:348:46: error: 'CONFIG_ESP32_PHY_MAX_TX_POWER' was not declared in this scope
 const wifi_country_t WM_COUNTRY_US{"US",1,11,CONFIG_ESP32_PHY_MAX_TX_POWER,WIFI_COUNTRY_POLICY_AUTO};
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/strings_en.h:348:46: note: suggested alternative: 'CONFIG_ESP_PHY_MAX_TX_POWER'
 const wifi_country_t WM_COUNTRY_US{"US",1,11,CONFIG_ESP32_PHY_MAX_TX_POWER,WIFI_COUNTRY_POLICY_AUTO};
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              CONFIG_ESP_PHY_MAX_TX_POWER
C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/strings_en.h:349:46: error: 'CONFIG_ESP32_PHY_MAX_TX_POWER' was not declared in this scope
 const wifi_country_t WM_COUNTRY_CN{"CN",1,13,CONFIG_ESP32_PHY_MAX_TX_POWER,WIFI_COUNTRY_POLICY_AUTO};
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/strings_en.h:349:46: note: suggested alternative: 'CONFIG_ESP_PHY_MAX_TX_POWER'
 const wifi_country_t WM_COUNTRY_CN{"CN",1,13,CONFIG_ESP32_PHY_MAX_TX_POWER,WIFI_COUNTRY_POLICY_AUTO};
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              CONFIG_ESP_PHY_MAX_TX_POWER
C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/strings_en.h:350:46: error: 'CONFIG_ESP32_PHY_MAX_TX_POWER' was not declared in this scope
 const wifi_country_t WM_COUNTRY_JP{"JP",1,14,CONFIG_ESP32_PHY_MAX_TX_POWER,WIFI_COUNTRY_POLICY_AUTO};
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Blanco\Documents\Arduino\libraries\WiFiManager/strings_en.h:350:46: note: suggested alternative: 'CONFIG_ESP_PHY_MAX_TX_POWER'
 const wifi_country_t WM_COUNTRY_JP{"JP",1,14,CONFIG_ESP32_PHY_MAX_TX_POWER,WIFI_COUNTRY_POLICY_AUTO};
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              CONFIG_ESP_PHY_MAX_TX_POWER
exit status 1
Error compiling for board UM TinyPICO.

**Comment by jonnybergdahl** [comment]
Nah, I used a TinyPICO for all development. And you do need the old audio shield as the newer ones need pins that are not even available on the WOPR.

The error you are getting is from the WiFiManager library though. Make sure you have the lastest released version - version 0.16.0, that compiles for me.

**Comment by sanderant** [comment]
That worked! I had to update another library as well, but it compiled and installed.
